name: Deploy Next.js app to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Latest version
        with:
          node-version: '20'  # Specify Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build and export Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
